services:
  frontend:
    build:
      context: ./FE 
      dockerfile: Dockerfile  
    ports:
      - "4173:4173"  
    networks:
      - app-network  

  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile 
    ports:
      - "8000:8000" 
    networks:
      - app-network
    volumes:
      - backend-data:/app/osm_files

networks:
  app-network:
    driver: bridge
    
volumes:
  backend-data: