version: "3.8"

services:
  frontend:
    build:
      context: ./FE 
      dockerfile: Dockerfile  
    ports:
      - "4173:4173"  
    networks:
      - app-network  

  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile 
    ports:
      - "8000:8000" 
    networks:
      - app-network 

networks:
  app-network:
    driver: bridge
