from common.map_enums import WorldSides, StyleKey
BoundsDict = dict[WorldSides, float]
DimensionsTuple  = tuple[float, float]
Point = tuple[float, float]
WantedArea = str | list[Point] | list[str | list[Point]]
OptDimensionsTuple = tuple[float | None, float | None]
WantedCategories = dict[str, set[str]]
UnwantedTags = dict[str, any]
FeatureStyles = dict[StyleKey, str | int | float]
FeaturesCategoryStyle = dict[str, FeatureStyles]
FeaturesCategoriesStyles = dict[str, tuple[FeaturesCategoryStyle, FeatureStyles]]